(deftheme zenburn-modified
  "Created 2016-05-31.")

(custom-theme-set-faces
 'zenburn-modified
 '(default ((t (:family "Ricty for Powerline" :foundry "unknown" :width normal :height 128 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#DCDCCC" :background "#3F3F3F" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#DCDCCC" :background "turquoise"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:bold t :foreground "#F0DFAF"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(highlight ((t (:background "#383838"))))
 '(region ((t (:background "#2B2B2B" :foreground "black"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "grey70"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#DCDCCC"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#7F9F7F"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#D0BF8F"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#F0DFAF"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#D0BF8F"))))
 '(fringe ((t (:background "#4F4F4F" :foreground "#DCDCCC"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :background "#2B2B2B" :foreground "#F0DFAF"))))
 '(tooltip ((t (:background "#4F4F4F" :foreground "#DCDCCC"))))
 '(mode-line ((t (:box nil :foreground "White" :background "DarkCyan"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#F0DFAF"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style released-button) :background "#383838" :foreground "#5F7F5F"))))
 '(isearch ((t (:background "#5F5F5F" :weight bold :foreground "#D0BF8F"))))
 '(isearch-fail ((t (:background "#8C5353" :foreground "#DCDCCC"))))
 '(lazy-highlight ((t (:background "#383838" :weight bold :foreground "#D0BF8F"))))
 '(match ((t (:weight bold :foreground "#DFAF8F" :background "#2B2B2B"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'zenburn-modified)
